 INSERT INTO instruments (ticker, name, instrument_type, exchange) VALUES
  -- Indices
  ('NIFTY50',            'Nifty 50 Index',                                  'index',        'NSE'),
  ('SENSEX',             'BSE Sensex Index',                                'index',        'BSE'),
  ('NIFTYMIDCAP150',     'Nifty Midcap 150 Index',                          'index',        'NSE'),
  ('NIFTYSMALLCAP250',   'Nifty Smallcap 250 Index',                        'index',        'NSE'),
  ('NIFTYNEXT50',        'Nifty Next 50 Index',                             'index',        'NSE'),
  -- Large Cap
  ('MIRAE-LC',           'Mirae Asset Large Cap Fund',                      'mutual_fund',  'AMFI'),
  ('AXIS-BC',            'Axis Bluechip Fund',                              'mutual_fund',  'AMFI'),
  ('HDFC-T100',          'HDFC Top 100 Fund',                               'mutual_fund',  'AMFI'),
  ('SBI-BC',             'SBI Bluechip Fund',                               'mutual_fund',  'AMFI'),
  ('KOTAK-BC',           'Kotak Bluechip Fund',                             'mutual_fund',  'AMFI'),
  ('ICICI-BC',           'ICICI Prudential Bluechip Fund',                  'mutual_fund',  'AMFI'),
  ('NIPPON-LC',          'Nippon India Large Cap Fund',                     'mutual_fund',  'AMFI'),
  ('CANARA-BC',          'Canara Robeco Bluechip Equity Fund',              'mutual_fund',  'AMFI'),
  ('UTI-MASTERSHARE',    'UTI Mastershare Unit Scheme',                     'mutual_fund',  'AMFI'),
  ('FRANKLIN-LC',        'Franklin India Bluechip Fund',                    'mutual_fund',  'AMFI'),
  -- Mid Cap
  ('HDFC-MID',           'HDFC Mid-Cap Opportunities Fund',                 'mutual_fund',  'AMFI'),
  ('AXIS-MID',           'Axis Midcap Fund',                                'mutual_fund',  'AMFI'),
  ('KOTAK-EMERG',        'Kotak Emerging Equity Fund',                      'mutual_fund',  'AMFI'),
  ('DSP-MID',            'DSP Midcap Fund',                                 'mutual_fund',  'AMFI'),
  ('NIPPON-GROWTH',      'Nippon India Growth Fund',                        'mutual_fund',  'AMFI'),
  ('MIRAE-MID',          'Mirae Asset Midcap Fund',                         'mutual_fund',  'AMFI'),
  ('SBI-MAG-MID',        'SBI Magnum Midcap Fund',                          'mutual_fund',  'AMFI'),
  ('PGIM-MID',           'PGIM India Midcap Opportunities Fund',            'mutual_fund',  'AMFI'),
  ('EDELWEISS-MID',      'Edelweiss Mid Cap Fund',                          'mutual_fund',  'AMFI'),
  -- Small Cap
  ('NIPPON-SC',          'Nippon India Small Cap Fund',                     'mutual_fund',  'AMFI'),
  ('SBI-SC',             'SBI Small Cap Fund',                              'mutual_fund',  'AMFI'),
  ('AXIS-SC',            'Axis Small Cap Fund',                             'mutual_fund',  'AMFI'),
  ('KOTAK-SC',           'Kotak Small Cap Fund',                            'mutual_fund',  'AMFI'),
  ('DSP-SC',             'DSP Small Cap Fund',                              'mutual_fund',  'AMFI'),
  ('HDFC-SC',            'HDFC Small Cap Fund',                             'mutual_fund',  'AMFI'),
  ('CANARA-SC',          'Canara Robeco Small Cap Fund',                    'mutual_fund',  'AMFI'),
  ('QUANT-SC',           'Quant Small Cap Fund',                            'mutual_fund',  'AMFI'),
  -- Flexi / Multi Cap
  ('PPFAS-FC',           'Parag Parikh Flexi Cap Fund',                     'mutual_fund',  'AMFI'),
  ('HDFC-FC',            'HDFC Flexi Cap Fund',                             'mutual_fund',  'AMFI'),
  ('KOTAK-FX',           'Kotak Flexicap Fund',                             'mutual_fund',  'AMFI'),
  ('UTI-FX',             'UTI Flexicap Fund',                               'mutual_fund',  'AMFI'),
  ('DSP-FC',             'DSP Flexi Cap Fund',                              'mutual_fund',  'AMFI'),
  ('AXIS-FC',            'Axis Focused 25 Fund',                            'mutual_fund',  'AMFI'),
  ('MIRAE-FC',           'Mirae Asset Flexi Cap Fund',                      'mutual_fund',  'AMFI'),
  -- ELSS
  ('AXIS-ELSS',          'Axis Long Term Equity Fund',                      'mutual_fund',  'AMFI'),
  ('MIRAE-ELSS',         'Mirae Asset Tax Saver Fund',                      'mutual_fund',  'AMFI'),
  ('KOTAK-ELSS',         'Kotak Tax Saver Fund',                            'mutual_fund',  'AMFI'),
  ('SBI-ELSS',           'SBI Long Term Equity Fund',                       'mutual_fund',  'AMFI'),
  ('HDFC-ELSS',          'HDFC TaxSaver Fund',                              'mutual_fund',  'AMFI'),
  ('QUANT-ELSS',         'Quant Tax Plan',                                  'mutual_fund',  'AMFI'),
  -- Index Funds
  ('UTI-N50-IDX',        'UTI Nifty 50 Index Fund',                         'mutual_fund',  'AMFI'),
  ('HDFC-N50-IDX',       'HDFC Index Fund Nifty 50 Plan',                   'mutual_fund',  'AMFI'),
  ('SBI-N50-IDX',        'SBI Nifty Index Fund',                            'mutual_fund',  'AMFI'),
  ('NIPPON-N50-IDX',     'Nippon India Index Fund Nifty 50 Plan',           'mutual_fund',  'AMFI'),
  ('MOTILAL-N50-IDX',    'Motilal Oswal Nifty 50 Index Fund',               'mutual_fund',  'AMFI'),
  ('ICICI-N50-IDX',      'ICICI Prudential Nifty 50 Index Fund',            'mutual_fund',  'AMFI'),
  ('MOTILAL-MID150-IDX', 'Motilal Oswal Nifty Midcap 150 Index Fund',       'mutual_fund',  'AMFI'),
  ('NAVI-N50-IDX',       'Navi Nifty 50 Index Fund',                        'mutual_fund',  'AMFI'),
  -- Debt
  ('HDFC-ST-DEBT',       'HDFC Short Term Debt Fund',                       'mutual_fund',  'AMFI'),
  ('KOTAK-BOND-ST',      'Kotak Bond Short Term Plan',                      'mutual_fund',  'AMFI'),
  ('AXIS-BPSU',          'Axis Banking and PSU Debt Fund',                  'mutual_fund',  'AMFI'),
  ('ICICI-CORP-BOND',    'ICICI Prudential Corporate Bond Fund',            'mutual_fund',  'AMFI'),
  ('NIPPON-ST',          'Nippon India Short Term Fund',                    'mutual_fund',  'AMFI'),
  -- Liquid
  ('HDFC-LIQ',           'HDFC Liquid Fund',                                'mutual_fund',  'AMFI'),
  ('SBI-LIQ',            'SBI Liquid Fund',                                 'mutual_fund',  'AMFI'),
  ('AXIS-LIQ',           'Axis Liquid Fund',                                'mutual_fund',  'AMFI'),
  ('KOTAK-LIQ',          'Kotak Liquid Fund',                               'mutual_fund',  'AMFI'),
  ('MIRAE-CASH',         'Mirae Asset Cash Management Fund',                'mutual_fund',  'AMFI'),
  -- Gold
  ('SBI-GOLD',           'SBI Gold Fund',                                   'gold',         'AMFI'),
  ('NIPPON-GOLD',        'Nippon India Gold Savings Fund',                  'gold',         'AMFI'),
  ('HDFC-GOLD',          'HDFC Gold Fund',                                  'gold',         'AMFI'),
  ('KOTAK-GOLD',         'Kotak Gold Fund',                                 'gold',         'AMFI'),
  -- ETFs
  ('NIFTYBEES',          'Nippon India ETF Nifty BeES',                     'etf',          'NSE'),
  ('GOLDBEES',           'Nippon India ETF Gold BeES',                      'etf',          'NSE'),
  ('JUNIORBEES',         'Nippon India ETF Junior BeES (N100)',              'etf',          'NSE'),
  ('CPSEETF',            'Nippon India ETF CPSE',                           'etf',          'NSE'),
  ('ICICINIFTY',         'ICICI Prudential Nifty ETF',                      'etf',          'NSE'),
  ('BANKBEES',           'Nippon India ETF Bank BeES',                      'etf',          'NSE'),
  ('UTINIFTETF',         'UTI Nifty 50 ETF',                                'etf',          'NSE'),
  ('HDFCSENSEX',         'HDFC Sensex ETF',                                 'etf',          'BSE'),
  ('MON100',             'Motilal Oswal Nasdaq 100 ETF',                    'etf',          'NSE'),
  ('SETFNN50',           'SBI Nifty Next 50 ETF',                           'etf',          'NSE'),
  ('LIQUIDBEES',         'Nippon India ETF Liquid BeES',                    'etf',          'NSE'),
  ('SILVRETF',           'Mirae Asset Silver ETF',                          'etf',          'NSE'),
  ('ITBEES',             'Nippon India ETF Nifty IT',                       'etf',          'NSE'),
  ('PSUBNKBEES',         'Nippon India ETF PSU Bank BeES',                  'etf',          'NSE'),
  -- Fixed Return
  ('FD-7PCT',            'Fixed Deposit (7% p.a.)',                         'fixed_return', NULL),
  ('FD-8PCT',            'Fixed Deposit (8% p.a.)',                         'fixed_return', NULL),
  ('PPF',                'Public Provident Fund (PPF 7.1% p.a.)',           'fixed_return', NULL),
  ('SUKANYA',            'Sukanya Samriddhi Yojana (8.2% p.a.)',            'fixed_return', NULL),
  -- ── Nifty 50 Equity Stocks ───────────────────────────────────────────────────
  ('RELIANCE',           'Reliance Industries',                             'equity',       'NSE'),
  ('TCS',                'Tata Consultancy Services',                       'equity',       'NSE'),
  ('HDFCBANK',           'HDFC Bank',                                       'equity',       'NSE'),
  ('BHARTIARTL',         'Bharti Airtel',                                   'equity',       'NSE'),
  ('ICICIBANK',          'ICICI Bank',                                      'equity',       'NSE'),
  ('INFOSYS',            'Infosys',                                         'equity',       'NSE'),
  ('SBIN',               'State Bank of India',                             'equity',       'NSE'),
  ('HINDUNILVR',         'Hindustan Unilever',                              'equity',       'NSE'),
  ('ITC',                'ITC',                                             'equity',       'NSE'),
  ('KOTAKBANK',          'Kotak Mahindra Bank',                             'equity',       'NSE'),
  ('LT',                 'Larsen & Toubro',                                 'equity',       'NSE'),
  ('AXISBANK',           'Axis Bank',                                       'equity',       'NSE'),
  ('BAJFINANCE',         'Bajaj Finance',                                   'equity',       'NSE'),
  ('BAJAJ-AUTO',         'Bajaj Auto',                                      'equity',       'NSE'),
  ('MARUTI',             'Maruti Suzuki India',                             'equity',       'NSE'),
  ('NTPC',               'NTPC',                                            'equity',       'NSE'),
  ('POWERGRID',          'Power Grid Corporation',                          'equity',       'NSE'),
  ('ONGC',               'Oil and Natural Gas Corporation',                 'equity',       'NSE'),
  ('SUNPHARMA',          'Sun Pharmaceutical Industries',                   'equity',       'NSE'),
  ('TATAMOTORS',         'Tata Motors',                                     'equity',       'NSE'),
  ('WIPRO',              'Wipro',                                           'equity',       'NSE'),
  ('HCLTECH',            'HCL Technologies',                                'equity',       'NSE'),
  ('TECHM',              'Tech Mahindra',                                   'equity',       'NSE'),
  ('TITAN',              'Titan Company',                                   'equity',       'NSE'),
  ('ASIANPAINT',         'Asian Paints',                                    'equity',       'NSE'),
  ('NESTLEIND',          'Nestlé India',                                    'equity',       'NSE'),
  ('ULTRACEMCO',         'UltraTech Cement',                                'equity',       'NSE'),
  ('GRASIM',             'Grasim Industries',                               'equity',       'NSE'),
  ('BRITANNIA',          'Britannia Industries',                            'equity',       'NSE'),
  ('CIPLA',              'Cipla',                                           'equity',       'NSE'),
  ('JSWSTEEL',           'JSW Steel',                                       'equity',       'NSE'),
  ('TATASTEEL',          'Tata Steel',                                      'equity',       'NSE'),
  ('HINDALCO',           'Hindalco Industries',                             'equity',       'NSE'),
  ('COALINDIA',          'Coal India',                                      'equity',       'NSE'),
  ('ADANIPORTS',         'Adani Ports and SEZ',                             'equity',       'NSE'),
  ('DRREDDY',            'Dr. Reddy''s Laboratories',                       'equity',       'NSE'),
  ('APOLLOHOSP',         'Apollo Hospitals Enterprise',                     'equity',       'NSE'),
  ('BPCL',               'Bharat Petroleum Corporation',                    'equity',       'NSE'),
  ('EICHERMOT',          'Eicher Motors',                                   'equity',       'NSE'),
  ('DIVISLAB',           'Divi''s Laboratories',                            'equity',       'NSE'),
  ('BAJAJFINSV',         'Bajaj Finserv',                                   'equity',       'NSE'),
  ('SBILIFE',            'SBI Life Insurance Company',                      'equity',       'NSE'),
  ('HDFCLIFE',           'HDFC Life Insurance Company',                     'equity',       'NSE'),
  ('MNM',                'Mahindra & Mahindra',                             'equity',       'NSE'),
  ('INDUSINDBK',         'IndusInd Bank',                                   'equity',       'NSE'),
  ('TATACONSUM',         'Tata Consumer Products',                          'equity',       'NSE'),
  ('HEROMOTOCO',         'Hero MotoCorp',                                   'equity',       'NSE'),
  ('ADANIENT',           'Adani Enterprises',                               'equity',       'NSE'),
  ('SHREECEM',           'Shree Cement',                                    'equity',       'NSE'),
  ('TRENT',              'Trent',                                           'equity',       'NSE')
  ON CONFLICT (ticker) DO UPDATE
    SET name             = EXCLUDED.name,
        instrument_type  = EXCLUDED.instrument_type,
        exchange         = EXCLUDED.exchange;